global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "fastapi"
    static_configs:
      - targets: ["api:8001"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
